import { Renderer2 } from '@angular/core';
import { OnInit, OnDestroy, SimpleChanges, OnChanges, ChangeDetectorRef, EventEmitter, ElementRef, AfterViewInit } from '@angular/core';
import { ControlValueAccessor, Validator, FormControl } from '@angular/forms';
import { FilterSettings } from './ser-filter.interface';
import { Subject } from 'rxjs';
import { SerFilterListFilterPipe } from './ser-filter-list-filter.pipe';
import { hasValue } from '../../utils/check';
import { SDBadgeDirective, SDItemDirective } from '../select/ser-select-menu-item.directive';
export declare class SerFilterComponent implements OnInit, ControlValueAccessor, OnChanges, Validator, AfterViewInit, OnDestroy {
    _elementRef: ElementRef;
    private cdr;
    private _renderer;
    data: any[];
    settings: FilterSettings;
    loading: boolean;
    multiple: boolean;
    label: string;
    onSelect: EventEmitter<any>;
    onDeSelect: EventEmitter<any>;
    onSelectAll: EventEmitter<Array<any>>;
    onDeSelectAll: EventEmitter<Array<any>>;
    onOpen: EventEmitter<any>;
    onClose: EventEmitter<any>;
    onScrollToEnd: EventEmitter<any>;
    onFilterSelectAll: EventEmitter<Array<any>>;
    onFilterDeSelectAll: EventEmitter<Array<any>>;
    onAddFilterNewItem: EventEmitter<any>;
    onGroupSelect: EventEmitter<any>;
    onGroupDeSelect: EventEmitter<any>;
    itemTempl: SDItemDirective;
    badgeTempl: SDBadgeDirective;
    searchInput: ElementRef;
    selectedListElem: ElementRef;
    dropdownListElem: ElementRef;
    isDisabled: boolean;
    isActive: boolean;
    searchTerm$: Subject<string>;
    filterPipe: SerFilterListFilterPipe;
    selectedItems: any[];
    isSelectAll: boolean;
    isFilterSelectAll: boolean;
    groupedData: any[];
    filter: any;
    chunkArray: any[];
    scrollTop: any;
    chunkIndex: any[];
    cachedItems: any[];
    groupCachedItems: any[];
    totalRows: any;
    itemHeight: any;
    screenItemsLen: any;
    totalHeight: any;
    scroller: any;
    selectedListHeight: any;
    filterLength: any;
    viewPortItems: any;
    labelActive: boolean;
    item: any;
    private dropdownSubs;
    private subscription;
    defaultSettings: FilterSettings;
    randomSize: boolean;
    parseError: boolean;
    filteredList: any;
    isDisabledItemPresent: boolean;
    hasValue: typeof hasValue;
    constructor(_elementRef: ElementRef, cdr: ChangeDetectorRef, _renderer: Renderer2, primaryKey: any, labelKey: any);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    onItemClick(item: any, k: number, e: any): boolean;
    validate(c: FormControl): any;
    writeValue(value: any): void;
    private onChangeCallback;
    registerOnChange(fn: any): void;
    private onTouchedCallback;
    registerOnTouched(fn: any): void;
    setDisabledState?(isDisabled: boolean): void;
    trackByFn(item: any): any;
    isSelected(clickedItem: any): boolean;
    addSelected(item: any): void;
    removeSelected(clickedItem: any): void;
    toggleDropdown(evt: any): boolean;
    openDropdown(): boolean;
    closeDropdown(): void;
    setPositionDropdown(): void;
    toggleSelectAll(): void;
    toggleFilterSelectAll(): void;
    clearSearch(): void;
    onFilterChange(data: any): void;
    cloneArray(arr: any): any;
    onScrollEnd(e: any): void;
    clearSelection(e: MouseEvent): void;
    getItemContext(item: any): any;
    ngOnDestroy(): void;
}
